[2024-12-06T22:20:52.567+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.Transform_weather_data manual__2024-12-06T19:13:15.012891+00:00 [queued]>
[2024-12-06T22:20:52.572+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.Transform_weather_data manual__2024-12-06T19:13:15.012891+00:00 [queued]>
[2024-12-06T22:20:52.573+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2024-12-06T22:20:52.581+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): Transform_weather_data> on 2024-12-06 19:13:15.012891+00:00
[2024-12-06T22:20:52.587+0000] {standard_task_runner.py:60} INFO - Started process 9548 to run task
[2024-12-06T22:20:52.590+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'Transform_weather_data', 'manual__2024-12-06T19:13:15.012891+00:00', '--job-id', '117', '--raw', '--subdir', 'DAGS_FOLDER/extract.py', '--cfg-path', '/tmp/tmpqk6qi8x3']
[2024-12-06T22:20:52.591+0000] {standard_task_runner.py:88} INFO - Job 117: Subtask Transform_weather_data
[2024-12-06T22:20:52.602+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-12-06T22:20:52.629+0000] {task_command.py:423} INFO - Running <TaskInstance: weather_dag.Transform_weather_data manual__2024-12-06T19:13:15.012891+00:00 [running]> on host 8a5e48d7ee4d
[2024-12-06T22:20:52.684+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='thiernosidybah232@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='Transform_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-06T19:13:15.012891+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-06T19:13:15.012891+00:00'
[2024-12-06T22:20:52.695+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extract.py", line 27, in transform_data
    city = data["name"]
TypeError: 'NoneType' object is not subscriptable
[2024-12-06T22:20:52.704+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_dag, task_id=Transform_weather_data, execution_date=20241206T191315, start_date=20241206T222052, end_date=20241206T222052
[2024-12-06T22:20:52.713+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 117 for task Transform_weather_data ('NoneType' object is not subscriptable; 9548)
[2024-12-06T22:20:52.721+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-12-06T22:20:52.743+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
