[2024-12-07T16:11:39.429+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.insert_book_data manual__2024-12-07T16:11:31.490676+00:00 [queued]>
[2024-12-07T16:11:39.437+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.insert_book_data manual__2024-12-07T16:11:31.490676+00:00 [queued]>
[2024-12-07T16:11:39.437+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2024-12-07T16:11:39.446+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): insert_book_data> on 2024-12-07 16:11:31.490676+00:00
[2024-12-07T16:11:39.452+0000] {standard_task_runner.py:60} INFO - Started process 3253 to run task
[2024-12-07T16:11:39.456+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'insert_book_data', 'manual__2024-12-07T16:11:31.490676+00:00', '--job-id', '160', '--raw', '--subdir', 'DAGS_FOLDER/extract.py', '--cfg-path', '/tmp/tmpbwpa6qqi']
[2024-12-07T16:11:39.458+0000] {standard_task_runner.py:88} INFO - Job 160: Subtask insert_book_data
[2024-12-07T16:11:39.473+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-12-07T16:11:39.512+0000] {task_command.py:423} INFO - Running <TaskInstance: weather_dag.insert_book_data manual__2024-12-07T16:11:31.490676+00:00 [running]> on host 8271fbcad3f4
[2024-12-07T16:11:39.597+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='thiernosidybah232@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='insert_book_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-07T16:11:31.490676+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-07T16:11:31.490676+00:00'
[2024-12-07T16:11:39.635+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extract.py", line 65, in insert_book_data_into_postgre
    if not data:
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 1466, in __nonzero__
    raise ValueError(
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
[2024-12-07T16:11:39.643+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_dag, task_id=insert_book_data, execution_date=20241207T161131, start_date=20241207T161139, end_date=20241207T161139
[2024-12-07T16:11:39.650+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 160 for task insert_book_data (The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().; 3253)
[2024-12-07T16:11:39.668+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-12-07T16:11:39.697+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
