[2024-12-07T16:03:03.838+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.Transform_weather_data manual__2024-12-07T16:02:58.528358+00:00 [queued]>
[2024-12-07T16:03:03.843+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.Transform_weather_data manual__2024-12-07T16:02:58.528358+00:00 [queued]>
[2024-12-07T16:03:03.843+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2024-12-07T16:03:03.851+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): Transform_weather_data> on 2024-12-07 16:02:58.528358+00:00
[2024-12-07T16:03:03.855+0000] {standard_task_runner.py:60} INFO - Started process 2845 to run task
[2024-12-07T16:03:03.858+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'Transform_weather_data', 'manual__2024-12-07T16:02:58.528358+00:00', '--job-id', '144', '--raw', '--subdir', 'DAGS_FOLDER/extract.py', '--cfg-path', '/tmp/tmp6x8tib1_']
[2024-12-07T16:03:03.859+0000] {standard_task_runner.py:88} INFO - Job 144: Subtask Transform_weather_data
[2024-12-07T16:03:03.869+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-12-07T16:03:03.895+0000] {task_command.py:423} INFO - Running <TaskInstance: weather_dag.Transform_weather_data manual__2024-12-07T16:02:58.528358+00:00 [running]> on host 8271fbcad3f4
[2024-12-07T16:03:03.951+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='thiernosidybah232@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='Transform_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-07T16:02:58.528358+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-07T16:02:58.528358+00:00'
[2024-12-07T16:03:03.970+0000] {xcom.py:664} ERROR - Object of type Timestamp is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2024-12-07T16:03:03.971+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/serialization/serde.py", line 180, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'pandas._libs.tslibs.timestamps.Timestamp'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/extract.py", line 60, in transform_data
    task_instance.xcom_push(key = "book_data", value = dataset.to_dict("records"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2980, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 247, in set
    value = cls.serialize_value(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 662, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Timestamp is not JSON serializable
[2024-12-07T16:03:03.978+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_dag, task_id=Transform_weather_data, execution_date=20241207T160258, start_date=20241207T160303, end_date=20241207T160303
[2024-12-07T16:03:03.984+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 144 for task Transform_weather_data (Object of type Timestamp is not JSON serializable; 2845)
[2024-12-07T16:03:03.989+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-12-07T16:03:04.004+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
